apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: vforum
spec:
  ports:
    - port: 3306
  selector:
    app: vforum
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: vforum
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: vforum
spec:
  selector:
    matchLabels:
      app: vforum
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vforum
        tier: mysql
    spec:
      containers:
      - image: cskvm/mysql_db:latest
        name: mysqldb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Vmware1!
        ports:
        - containerPort: 3306
          name: mysqldb
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
