apiVersion: v1
kind: Service
metadata:
  name: vflask
  labels:
    app: vforum
spec:
  ports:
    - port: 80
  selector:
    app: vforum
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: vflask
  labels:
    app: vforum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vforum
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vforum
        tier: frontend
    spec:
      containers:
      - image: cskvm/vflask:v12
        imagePullPolicy: Always
        name: vforum
        ports:
        - containerPort: 80
          name: vforum
